### ISSUE TITLE
n_appearance_parameters not updated in patch_aam

### ISSUE THREAD

**Issue by grigorisg9gr** [menpo/menpowidgets#2]
The following setup can be followed to reproduce the error: 
1. Train a pyramid of patch AAM with enough images (>appearance components of the fitter). 
2. Use visualize_patch_aam() to visualise and then from level 0 (default), move to level 1. 
3. If you try to move to level 0 again, it crashes when trying to create the menpofit instance (due to the not updated value of n_appearance_parameters).

**Comment by nontas** [comment]
This has been fixed
