### ISSUE TITLE
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version

### ISSUE THREAD

**Issue by taopanpan** [menpo/menpowidgets#23]
with the newest anaconda, it will show this error. And the widgets cannot show out. how to solve it ?

**Comment by patricksnape** [comment]
Can you please provide the output of `conda list` in the environment that menpo is installed in?

**Comment by taopanpan** [comment]
I solved by follow the installation tutorial,with a new python environment. if don't do it ,just with the version of anaconda 4.2.0 and conda install menpo will show that error.
