### ISSUE TITLE
Widgets sometimes fail with no message

### ISSUE THREAD

**Issue by grigorisg9gr** [menpo/menpowidgets#3]
In an active notebook (with length of images_t = 80) this happened: 

![visualize_images_failing](https://cloud.githubusercontent.com/assets/2621492/11215865/3ca8e508-8d40-11e5-8c38-877d0db83064.png)

In other words with no debugging message the widgets fail, even if i can still visualise the images individually. I suppose the lack of debugging message is due to the command 'ipydisplay.clear_output(wait=True)'. Maybe in case of failure the output should not be cleared, it will be easier for debugging. 

If i start the notebook, run the commands again the original command works fine.

**Comment by patricksnape** [comment]
All the widgets?

**Comment by grigorisg9gr** [comment]
Didn't try with the rest, so cannot confirm that. If it happens again, I can try the rest of the widgets.

**Comment by nontas** [comment]
Do you still see this @grigorisg9gr ?

**Comment by grigorisg9gr** [comment]
Nope. Haven't noticed it for a while. Probably it was fixed with one of the previous changes. 
You can close it.
