### ISSUE TITLE
Installation issues with Conda and compatibility issues with main menpo library

### ISSUE THREAD

**Issue by LucaCappelletti94** [menpo/menpowidgets#36]
Hello all and thank you for making this project.

After having attempted to install `menpowidgets` from Conda using the following command:

```bash
conda install -c menpo menpowidgets
```

I got the error that I need to be in a python `3.5.x` environment (amongst others):

```bash
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - menpowidgets -> python[version='2.7.*|3.5.*|3.4.*']

Your python: python=3.7
```

Therefore I created a python `3.5.x` environment using the following command:

```bash
conda create -n menpo python=3.5 anaconda
```

But now, when I try to install menpo from condo using the command:

```bash
conda install -c conda-forge menpo
```

I get the error that menpo does not support python versions earlier than `3.6`.

```bash
Specifications:

  - menpo -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=3.5
```

This would lead me to believe that menpowidgets is no longer compatible with menpo. Is this the case?

How can I try to visualize the models? Without these visualization tools, I believe working with the models will get very difficult for a neophyte.

Additionally, when trying to install menpowidgets in the `menpo` envinronment using again the command:

```bash
conda install -c menpo menpowidgets
```

I got the error:

```bash
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                   

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

Could you point me in the right direction?

The OS I'm using is:

```bash
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

Thank you for your help,
Luca

**Comment by patricksnape** [comment]
Fixed as of menpowidgets 0.4.0 - install using pip or conda-forge
